Repository AGH-Narzedzia-Informatyczne-2023-2024/PyPou, pull requests merged in 2023-11, with the labels that each got.

#19 Branch esujeta
  PySaga/PyPou.png
  PySaga/PySaga.py
Labels: minigra

#21 dodano plik do Bartlomiej_Wolny_Branch
  wolny_branch.txt
Labels: documentation

#24 Dodanie pliku "Algebra macierzy", funkcjonalności naukowej
  Algebra macierzy.pdf
Labels: enhancement
